# Generated by Django 4.2.3 on 2023-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
