# Generated by Django 4.2.3 on 2023-07-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delivery_sender_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
