# Generated by Django 4.2.3 on 2023-07-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delivery_destination_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000),
        ),
    ]
